<?php
/**
 * CsrDecodeCsrResponseDataTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  &quot;Panthera\Openprovider&quot;
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace &quot;Panthera\Openprovider&quot;\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CsrDecodeCsrResponseDataTest Class Doc Comment
 *
 * @category    Class
 * @description CsrDecodeCsrResponseData
 * @package     &quot;Panthera\Openprovider&quot;
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CsrDecodeCsrResponseDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CsrDecodeCsrResponseData"
     */
    public function testCsrDecodeCsrResponseData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "domain_names_count"
     */
    public function testPropertyDomainNamesCount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "public_key"
     */
    public function testPropertyPublicKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "signature_hash_algorithm"
     */
    public function testPropertySignatureHashAlgorithm()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "subject_alternative_name"
     */
    public function testPropertySubjectAlternativeName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
