<?php
/**
 * CustomerCustomerAdditionalDataTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  &quot;Panthera\Openprovider&quot;
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace &quot;Panthera\Openprovider&quot;\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CustomerCustomerAdditionalDataTest Class Doc Comment
 *
 * @category    Class
 * @description CustomerCustomerAdditionalData
 * @package     &quot;Panthera\Openprovider&quot;
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CustomerCustomerAdditionalDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CustomerCustomerAdditionalData"
     */
    public function testCustomerCustomerAdditionalData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "attached_files"
     */
    public function testPropertyAttachedFiles()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "birth_address"
     */
    public function testPropertyBirthAddress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "birth_city"
     */
    public function testPropertyBirthCity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "birth_country"
     */
    public function testPropertyBirthCountry()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "birth_date"
     */
    public function testPropertyBirthDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "birth_state"
     */
    public function testPropertyBirthState()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "birth_zipcode"
     */
    public function testPropertyBirthZipcode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_registration_city"
     */
    public function testPropertyCompanyRegistrationCity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_registration_number"
     */
    public function testPropertyCompanyRegistrationNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_registration_subscription_date"
     */
    public function testPropertyCompanyRegistrationSubscriptionDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_url"
     */
    public function testPropertyCompanyUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "headquarters_address"
     */
    public function testPropertyHeadquartersAddress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "headquarters_city"
     */
    public function testPropertyHeadquartersCity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "headquarters_country"
     */
    public function testPropertyHeadquartersCountry()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "headquarters_state"
     */
    public function testPropertyHeadquartersState()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "headquarters_zipcode"
     */
    public function testPropertyHeadquartersZipcode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "passport_number"
     */
    public function testPropertyPassportNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "social_security_number"
     */
    public function testPropertySocialSecurityNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trading_name"
     */
    public function testPropertyTradingName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
