<?php
/**
 * CustomerExtensionDataTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  &quot;Panthera\Openprovider&quot;
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace &quot;Panthera\Openprovider&quot;\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CustomerExtensionDataTest Class Doc Comment
 *
 * @category    Class
 * @description CustomerExtensionData
 * @package     &quot;Panthera\Openprovider&quot;
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CustomerExtensionDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CustomerExtensionData"
     */
    public function testCustomerExtensionData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "admin_type"
     */
    public function testPropertyAdminType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "applicant_purpose"
     */
    public function testPropertyApplicantPurpose()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "birth_date"
     */
    public function testPropertyBirthDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_name_cyrillic"
     */
    public function testPropertyCompanyNameCyrillic()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_name_latin"
     */
    public function testPropertyCompanyNameLatin()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_registration_number"
     */
    public function testPropertyCompanyRegistrationNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "contact_title"
     */
    public function testPropertyContactTitle()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "country_of_citizenship"
     */
    public function testPropertyCountryOfCitizenship()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "customer_uin"
     */
    public function testPropertyCustomerUin()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ens_auth_id"
     */
    public function testPropertyEnsAuthId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ens_key"
     */
    public function testPropertyEnsKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "first_name_cyrillic"
     */
    public function testPropertyFirstNameCyrillic()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "first_name_latin"
     */
    public function testPropertyFirstNameLatin()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hr_member"
     */
    public function testPropertyHrMember()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "industry_class"
     */
    public function testPropertyIndustryClass()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_private_enterpreneur"
     */
    public function testPropertyIsPrivateEnterpreneur()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "last_name_cyrillic"
     */
    public function testPropertyLastNameCyrillic()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "last_name_latin"
     */
    public function testPropertyLastNameLatin()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "legal_address_cyrillic"
     */
    public function testPropertyLegalAddressCyrillic()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "legal_type"
     */
    public function testPropertyLegalType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "middle_name_cyrillic"
     */
    public function testPropertyMiddleNameCyrillic()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "middle_name_latin"
     */
    public function testPropertyMiddleNameLatin()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "mobile_phone_number"
     */
    public function testPropertyMobilePhoneNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nexus_category"
     */
    public function testPropertyNexusCategory()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "org_type"
     */
    public function testPropertyOrgType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "passport_issue_date"
     */
    public function testPropertyPassportIssueDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "passport_issuer"
     */
    public function testPropertyPassportIssuer()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "passport_number"
     */
    public function testPropertyPassportNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "passport_series"
     */
    public function testPropertyPassportSeries()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "postal_address_cyrillic"
     */
    public function testPropertyPostalAddressCyrillic()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "social_security_number"
     */
    public function testPropertySocialSecurityNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tax_payer_number"
     */
    public function testPropertyTaxPayerNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "uin"
     */
    public function testPropertyUin()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "user_type"
     */
    public function testPropertyUserType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "vat"
     */
    public function testPropertyVat()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "website"
     */
    public function testPropertyWebsite()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "whois_email"
     */
    public function testPropertyWhoisEmail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
