<?php
/**
 * LicenseServiceApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  &quot;Panthera\Openprovider&quot;
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace &quot;Panthera\Openprovider&quot;\Test\Api;

use \&quot;Panthera\Openprovider&quot;\Configuration;
use \&quot;Panthera\Openprovider&quot;\ApiException;
use \&quot;Panthera\Openprovider&quot;\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * LicenseServiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  &quot;Panthera\Openprovider&quot;
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LicenseServiceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createPleskLicense
     *
     * Create plesk license.
     *
     */
    public function testCreatePleskLicense()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createVirtuozzoLicense
     *
     * Create virtuozzo license.
     *
     */
    public function testCreateVirtuozzoLicense()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deletePleskLicense
     *
     * Delete plesk license.
     *
     */
    public function testDeletePleskLicense()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteVirtuozzoLicense
     *
     * Delete virtuozzo license.
     *
     */
    public function testDeleteVirtuozzoLicense()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPleskKey
     *
     * Get plesk key.
     *
     */
    public function testGetPleskKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPleskLicense
     *
     * Get plesk license.
     *
     */
    public function testGetPleskLicense()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getVirtuozzoKey
     *
     * Get virtuozzo key.
     *
     */
    public function testGetVirtuozzoKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getVirtuozzoLicense
     *
     * Get virtuozzo license.
     *
     */
    public function testGetVirtuozzoLicense()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listItems
     *
     * List items.
     *
     */
    public function testListItems()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listLicensesWithPriceVersion
     *
     * List licenses with price version.
     *
     */
    public function testListLicensesWithPriceVersion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPleskLicenses
     *
     * List plesk licenses.
     *
     */
    public function testListPleskLicenses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listVirtuozzoLicenses
     *
     * List virtuozzo licenses.
     *
     */
    public function testListVirtuozzoLicenses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for resetHwid
     *
     * Reset hwid.
     *
     */
    public function testResetHwid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updatePleskLicense
     *
     * Update plesk license.
     *
     */
    public function testUpdatePleskLicense()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateVirtuozzoLicense
     *
     * Update virtuozzo license.
     *
     */
    public function testUpdateVirtuozzoLicense()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
