<?php
/**
 * ZoneServiceApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  &quot;Panthera\Openprovider&quot;
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace &quot;Panthera\Openprovider&quot;\Test\Api;

use \&quot;Panthera\Openprovider&quot;\Configuration;
use \&quot;Panthera\Openprovider&quot;\ApiException;
use \&quot;Panthera\Openprovider&quot;\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ZoneServiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  &quot;Panthera\Openprovider&quot;
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ZoneServiceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createZone
     *
     * Create zone.
     *
     */
    public function testCreateZone()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteZone
     *
     * Delete zone.
     *
     */
    public function testDeleteZone()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getZone
     *
     * Get zone.
     *
     */
    public function testGetZone()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listZones
     *
     * List zones.
     *
     */
    public function testListZones()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateZone
     *
     * Update zone.
     *
     */
    public function testUpdateZone()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
